version: '3.7'
services: 
    api: 
        ports:
            - "4193:4193"
        build: 
            context: ./server
            dockerfile: Dockerfile
        image: bill_generator
        container_name: app_bill_generator
        volumes:
            - ./server:/usr/src/bill_generator
        environment:
            DATABASE_URL: postgres://postgres:eatsleepcode@postgres:5432/db
    postgres:
        image: postgres
        ports:
            - "5432:5432"
        container_name: pg_container
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: eatsleepcode
            POSTGRES_DB: db
    frontend: 
        build: 
            context: ./client
            dockerfile: Dockerfile
        image: bill_generator_frontend
        ports: 
            - "3000:3000"
        volumes:
            - ./client:/usr/src/bill_generator_frontend
        links:
            - "api"
